
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdp.h"

/*
* The configuration table for devices
*/

XDp_Config XDp_ConfigTable[XPAR_XDP_NUM_INSTANCES] =
{
	{
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_DEVICE_ID,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_BASEADDR,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_S_AXI_ACLK,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_LANE_COUNT,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_LINK_RATE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_MAX_BITS_PER_COLOR,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_QUAD_PIXEL_ENABLE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_DUAL_PIXEL_ENABLE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_YCRCB_ENABLE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_YONLY_ENABLE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_GT_DATAWIDTH,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_SECONDARY_SUPPORT,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_AUDIO_CHANNELS,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_MST_ENABLE,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_NUMBER_OF_MST_STREAMS,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_PROTOCOL_SELECTION,
		XPAR_DP_RX_HIER_0_V_DP_RXSS1_0_DP_FLOW_DIRECTION
	}
};


