# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5.xci
# IP: The module: 'dpss_zcu102_rx_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_auto_ds_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5.xci
# IP: The module: 'dpss_zcu102_rx_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
