# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0.xci
# IP: The module: 'dpss_zcu102_rx_vid_phy_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper} -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/synth/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/synth/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0.xci
# IP: The module: 'dpss_zcu102_rx_vid_phy_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper} -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/synth/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/ip_0/synth/dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
