set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_6311_dp_0.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_6311_dp_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_6311_dp_0_clocks.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_6311_dp_0_clocks.xdc id:2 order:LATE scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:3 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:12 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:13 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:14 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:15 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:16 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:17 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:18 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:19 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:20 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:21 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:22 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_interrupt_inst/i_mode_change_interrupt_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_interrupt_inst/FSM_onehot_i_mode_change_interrupt_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/i_*_match_event_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-4 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/i_updated_timing_parameters_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "i_fifo_reset CDC-11 fix" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_main_inst/i_fifo_reset_reg*}]] -to   *PIN
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 40 -from [ get_clocks -of_objects [get_ports s_axi_aclk] ] -to  [get_clocks -of_objects [get_pins [list inst/core_top_inst/dport_link_inst/rx_vid_clk inst/core_top_inst/dport_link_inst/rx_vid_clk_stream2 inst/core_top_inst/dport_link_inst/rx_vid_clk_stream3 inst/core_top_inst/dport_link_inst/rx_vid_clk_stream4 inst/core_top_inst/rx_vid_clk inst/core_top_inst/rx_vid_clk_stream2 inst/core_top_inst/rx_vid_clk_stream3 inst/core_top_inst/rx_vid_clk_stream4]]]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 40 -from [get_clocks -of_objects [get_pins [list inst/core_top_inst/dport_link_inst/rx_vid_clk inst/core_top_inst/dport_link_inst/rx_vid_clk_stream2 inst/core_top_inst/dport_link_inst/rx_vid_clk_stream3 inst/core_top_inst/dport_link_inst/rx_vid_clk_stream4 inst/core_top_inst/rx_vid_clk inst/core_top_inst/rx_vid_clk_stream2 inst/core_top_inst/rx_vid_clk_stream3 inst/core_top_inst/rx_vid_clk_stream4]]] -to  [ get_clocks -of_objects [get_ports s_axi_aclk] ]
set_property src_info {type:SCOPED_XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 25 -from [ get_clocks -of_objects [get_ports s_axi_aclk] ] -to   [get_clocks -of_objects [get_ports rx_lnk_clk]  ]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 25 -from [get_clocks -of_objects [get_ports rx_lnk_clk] ] -to [ get_clocks -of_objects [get_ports s_axi_aclk] ]
set_property src_info {type:SCOPED_XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/cfg_rx_vidmode_regs_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/i_updated_timing_parameters_reg*}] -filter {REF_PIN_NAME == D}] -datapath_only 25
set_property src_info {type:SCOPED_XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/cfg_rx_vidmode_regs_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/i_*_match_event_reg*}] -filter {REF_PIN_NAME == D}] -datapath_only 25
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:3 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/gen_rx_secondary_streams[0].displayport_v8_1_2_rx_secondary_inst/displayport_v8_1_2_rx_sec_axis_inst/fifo_gen_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:12 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:13 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:14 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:15 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:16 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:17 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:18 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_0/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:19 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_1/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:20 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_2/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:21 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_2_rx_link_inst/displayport_v8_1_2_rx_main_inst/gen_user_modules[0].displayport_v8_1_2_rx_user_inst/displayport_v8_1_2_rx_user_fifo_lane_3/displayport_v8_1_2_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:22 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
