set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_clk_wiz_0_0/dpss_zcu102_rx_clk_wiz_0_0/dpss_zcu102_rx_clk_wiz_0_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_clk_wiz_0_0/dpss_zcu102_rx_clk_wiz_0_0/dpss_zcu102_rx_clk_wiz_0_0_in_context.xdc id:1 order:EARLY scoped_inst:dpss_zcu102_rx_i/clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_0_0/dpss_zcu102_rx_util_ds_buf_0_0/dpss_zcu102_rx_util_ds_buf_1_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_0_0/dpss_zcu102_rx_util_ds_buf_0_0/dpss_zcu102_rx_util_ds_buf_1_0_in_context.xdc id:2 order:EARLY scoped_inst:dpss_zcu102_rx_i/dp_rx_hier_0/util_ds_buf_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_1_0/dpss_zcu102_rx_util_ds_buf_1_0/dpss_zcu102_rx_util_ds_buf_1_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_1_0/dpss_zcu102_rx_util_ds_buf_1_0/dpss_zcu102_rx_util_ds_buf_1_0_in_context.xdc id:3 order:EARLY scoped_inst:dpss_zcu102_rx_i/dp_rx_hier_0/util_ds_buf_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/dpss_zcu102_rx_v_dp_rxss1_0_0/dpss_zcu102_rx_v_dp_rxss1_0_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/dpss_zcu102_rx_v_dp_rxss1_0_0/dpss_zcu102_rx_v_dp_rxss1_0_0_in_context.xdc id:4 order:EARLY scoped_inst:dpss_zcu102_rx_i/dp_rx_hier_0/v_dp_rxss1_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0_in_context.xdc id:5 order:EARLY scoped_inst:dpss_zcu102_rx_i/dp_rx_hier_0/vid_phy_controller_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_zynq_ultra_ps_e_0_0/dpss_zcu102_rx_zynq_ultra_ps_e_0_0/dpss_zcu102_rx_zynq_ultra_ps_e_0_0_in_context.xdc rfile:../../../v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_zynq_ultra_ps_e_0_0/dpss_zcu102_rx_zynq_ultra_ps_e_0_0/dpss_zcu102_rx_zynq_ultra_ps_e_0_0_in_context.xdc id:6 order:EARLY scoped_inst:dpss_zcu102_rx_i/zynq_ultra_ps_e_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/imports/top_zcu102.xdc rfile:../../../imports/top_zcu102.xdc id:7 order:LATE} [current_design]
current_instance dpss_zcu102_rx_i/clk_wiz_0
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.333 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 10.832 21.664} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
current_instance dpss_zcu102_rx_i/dp_rx_hier_0/util_ds_buf_0
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance dpss_zcu102_rx_i/dp_rx_hier_0/util_ds_buf_1
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance dpss_zcu102_rx_i/dp_rx_hier_0/v_dp_rxss1_0
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.469 [get_ports {}]
current_instance
current_instance dpss_zcu102_rx_i/dp_rx_hier_0/vid_phy_controller_0
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.469 [get_ports {}]
current_instance
current_instance dpss_zcu102_rx_i/zynq_ultra_ps_e_0
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {IBUF_DS_N[0]}]
set_property src_info {type:XDC file:7 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports {IBUF_DS_P[0]}]
set_property src_info {type:XDC file:7 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports {IBUF_DS_N1[0]}]
set_property src_info {type:XDC file:7 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {IBUF_DS_P1[0]}]
set_property src_info {type:XDC file:7 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {rx_hpd[0]}]
set_property src_info {type:XDC file:7 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {aux_rx_data_en_out_n_0[0]}]
set_property src_info {type:XDC file:7 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports aux_rx_data_out_0]
set_property src_info {type:XDC file:7 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L11 [get_ports aux_rx_data_in_0]
set_property src_info {type:XDC file:7 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -filter {REF_PIN_NAME=~ C} -of_objects [get_cells -hierarchical -filter {NAME=~ */drp_control_b0gtcommon_inst/DRPADDR_reg[*]}]] -to [get_pins -filter {REF_PIN_NAME=~ DRPADDR[*]} -of_objects [get_cells -hierarchical -filter {name=~*GTHE4_COMMON_PRIM_INST}]] 0.300
set_property src_info {type:XDC file:7 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -filter {REF_PIN_NAME=~ C} -of_objects [get_cells -hierarchical -filter {NAME=~ */drp_control_b0gtcommon_inst/DRPDI_reg[*]}]] -to [get_pins -filter {REF_PIN_NAME=~ DRPDI[*]} -of_objects [get_cells -hierarchical -filter {name=~*GTHE4_COMMON_PRIM_INST}]] 0.300
set_property src_info {type:XDC file:7 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -filter {REF_PIN_NAME=~ C} -of_objects [get_cells -hierarchical -filter {NAME=~ */drp_control_b0gtcommon_inst/DRPEN_reg}]] -to [get_pins -filter {REF_PIN_NAME=~ DRPEN} -of_objects [get_cells -hierarchical -filter {name=~*GTHE4_COMMON_PRIM_INST}]] 0.300
set_property src_info {type:XDC file:7 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -filter {REF_PIN_NAME=~ C} -of_objects [get_cells -hierarchical -filter {NAME=~ */drp_control_b0gtcommon_inst/DRPWE_reg}]] -to [get_pins -filter {REF_PIN_NAME=~ DRPWE} -of_objects [get_cells -hierarchical -filter {name=~*GTHE4_COMMON_PRIM_INST}]] 0.300
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC "" [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[26].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC "" [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[26].*gen_gthe4_channel_inst[1].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC "" [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[26].*gen_gthe4_channel_inst[2].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC "" [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[26].*gen_gthe4_channel_inst[3].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:XDC file:7 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {phy_rxn_in[0]}]
set_property src_info {type:XDC file:7 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {phy_rxp_in[0]}]
set_property src_info {type:XDC file:7 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {phy_rxn_in[1]}]
set_property src_info {type:XDC file:7 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {phy_rxp_in[1]}]
set_property src_info {type:XDC file:7 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F1 [get_ports {phy_rxn_in[2]}]
set_property src_info {type:XDC file:7 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {phy_rxp_in[2]}]
set_property src_info {type:XDC file:7 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {phy_rxn_in[3]}]
set_property src_info {type:XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {phy_rxp_in[3]}]
set_property src_info {type:XDC file:7 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports {B_SOURCE_AUX_DE[0]}]
set_property src_info {type:XDC file:7 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {B_SOURCE_RST[0]}]
set_property src_info {type:XDC file:7 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {pwd[0]}]
set_property src_info {type:XDC file:7 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports i2c_scl]
set_property src_info {type:XDC file:7 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports i2c_sda]
set_property src_info {type:XDC file:7 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
