# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/imports/top_zcu102.xdc

# Block Designs: bd/dpss_zcu102_rx/dpss_zcu102_rx.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx || ORIG_REF_NAME==dpss_zcu102_rx} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_axi_iic_0_0/dpss_zcu102_rx_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_axi_iic_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_axi_iic_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_axi_timer_0_0/dpss_zcu102_rx_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_axi_timer_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_axi_timer_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_clk_wiz_0_0/dpss_zcu102_rx_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_clk_wiz_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_clk_wiz_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_0_0/dpss_zcu102_rx_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_ds_buf_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_1_0/dpss_zcu102_rx_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_ds_buf_1_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_reduced_logic_0_0/dpss_zcu102_rx_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_reduced_logic_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_v_dp_rxss1_0_0/dpss_zcu102_rx_v_dp_rxss1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_v_dp_rxss1_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_v_dp_rxss1_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_edid_0_0/dpss_zcu102_rx_vid_edid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_edid_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_vid_edid_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_vid_phy_controller_0_0/dpss_zcu102_rx_vid_phy_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_vid_phy_controller_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_video_frame_crc_0_0/dpss_zcu102_rx_video_frame_crc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_video_frame_crc_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_video_frame_crc_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconcat_0_0/dpss_zcu102_rx_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconcat_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_xlconcat_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconstant_0_0/dpss_zcu102_rx_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconstant_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_xlconstant_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconstant_1_0/dpss_zcu102_rx_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconstant_1_0 || ORIG_REF_NAME==dpss_zcu102_rx_xlconstant_1_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconstant_2_0/dpss_zcu102_rx_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconstant_2_0 || ORIG_REF_NAME==dpss_zcu102_rx_xlconstant_2_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_2_0/dpss_zcu102_rx_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_ds_buf_2_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_ds_buf_3_0/dpss_zcu102_rx_util_ds_buf_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_ds_buf_3_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_ds_buf_3_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_vector_logic_0_0/dpss_zcu102_rx_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_vector_logic_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_vector_logic_1_0/dpss_zcu102_rx_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_vector_logic_1_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_vector_logic_2_0/dpss_zcu102_rx_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_vector_logic_2_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_vector_logic_3_0/dpss_zcu102_rx_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_vector_logic_3_0 || ORIG_REF_NAME==dpss_zcu102_rx_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_proc_sys_reset_0_0/dpss_zcu102_rx_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_proc_sys_reset_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xbar_0/dpss_zcu102_rx_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xbar_0 || ORIG_REF_NAME==dpss_zcu102_rx_xbar_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ps8_0_axi_periph_0/dpss_zcu102_rx_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ps8_0_axi_periph_0 || ORIG_REF_NAME==dpss_zcu102_rx_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_rst_ps8_0_99M_0/dpss_zcu102_rx_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_rst_ps8_0_99M_0 || ORIG_REF_NAME==dpss_zcu102_rx_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_system_ila_1_0/dpss_zcu102_rx_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_system_ila_1_0 || ORIG_REF_NAME==dpss_zcu102_rx_system_ila_1_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_system_ila_2_0/dpss_zcu102_rx_system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_system_ila_2_0 || ORIG_REF_NAME==dpss_zcu102_rx_system_ila_2_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_util_vector_logic_1_1/dpss_zcu102_rx_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_util_vector_logic_1_1 || ORIG_REF_NAME==dpss_zcu102_rx_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconcat_0_1/dpss_zcu102_rx_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconcat_0_1 || ORIG_REF_NAME==dpss_zcu102_rx_xlconcat_0_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconstant_0_1/dpss_zcu102_rx_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconstant_0_1 || ORIG_REF_NAME==dpss_zcu102_rx_xlconstant_0_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_xlconstant_1_1/dpss_zcu102_rx_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_xlconstant_1_1 || ORIG_REF_NAME==dpss_zcu102_rx_xlconstant_1_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_zynq_ultra_ps_e_0_0/dpss_zcu102_rx_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==dpss_zcu102_rx_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_0/dpss_zcu102_rx_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_0 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_0/dpss_zcu102_rx_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_0 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_0} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_1/dpss_zcu102_rx_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_1 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_1/dpss_zcu102_rx_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_1 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_1} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_2/dpss_zcu102_rx_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_2 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_2} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_2/dpss_zcu102_rx_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_2 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_2} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_3/dpss_zcu102_rx_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_3 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_3} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_3/dpss_zcu102_rx_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_3 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_3} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_4/dpss_zcu102_rx_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_4 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_4} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_4/dpss_zcu102_rx_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_4 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_4} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_ds_5/dpss_zcu102_rx_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_ds_5 || ORIG_REF_NAME==dpss_zcu102_rx_auto_ds_5} -quiet] -quiet

# IP: bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_auto_pc_5/dpss_zcu102_rx_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_auto_pc_5 || ORIG_REF_NAME==dpss_zcu102_rx_auto_pc_5} -quiet] -quiet

# XDC: bd/dpss_zcu102_rx/dpss_zcu102_rx_ooc.xdc
