# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/dpss_zcu102_rx_ddr4_0_0.xci
# IP: The module: 'dpss_zcu102_rx_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_1/dpss_zcu102_rx_ddr4_0_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_phy || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/bd_47c8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8 || ORIG_REF_NAME==bd_47c8} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_microblaze_I_0 || ORIG_REF_NAME==bd_47c8_microblaze_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_2/bd_47c8_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_0 || ORIG_REF_NAME==bd_47c8_ilmb_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_3/bd_47c8_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_0 || ORIG_REF_NAME==bd_47c8_dlmb_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_4/bd_47c8_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_5/bd_47c8_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_6/bd_47c8_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_lmb_bram_I_0 || ORIG_REF_NAME==bd_47c8_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_7/bd_47c8_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_8/bd_47c8_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_9/bd_47c8_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_47c8_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_10/bd_47c8_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_iomodule_0_0 || ORIG_REF_NAME==bd_47c8_iomodule_0_0} -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_1/par/dpss_zcu102_rx_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_microblaze_I_0 || ORIG_REF_NAME==bd_47c8_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_2/bd_47c8_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_0 || ORIG_REF_NAME==bd_47c8_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_3/bd_47c8_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_0 || ORIG_REF_NAME==bd_47c8_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_6/bd_47c8_lmb_bram_I_0_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_9/bd_47c8_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_10/bd_47c8_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_iomodule_0_0 || ORIG_REF_NAME==bd_47c8_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/bd_47c8_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/dpss_zcu102_rx_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/par/dpss_zcu102_rx_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/dpss_zcu102_rx_ddr4_0_0.xci
# IP: The module: 'dpss_zcu102_rx_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_1/dpss_zcu102_rx_ddr4_0_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_phy || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_phy} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/bd_47c8.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8 || ORIG_REF_NAME==bd_47c8} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_microblaze_I_0 || ORIG_REF_NAME==bd_47c8_microblaze_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_2/bd_47c8_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_0 || ORIG_REF_NAME==bd_47c8_ilmb_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_3/bd_47c8_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_0 || ORIG_REF_NAME==bd_47c8_dlmb_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_4/bd_47c8_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_5/bd_47c8_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_6/bd_47c8_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_lmb_bram_I_0 || ORIG_REF_NAME==bd_47c8_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_7/bd_47c8_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_8/bd_47c8_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_47c8_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_9/bd_47c8_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_47c8_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_10/bd_47c8_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_47c8_iomodule_0_0 || ORIG_REF_NAME==bd_47c8_iomodule_0_0} -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_1/par/dpss_zcu102_rx_ddr4_0_0_phy_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_microblaze_I_0 || ORIG_REF_NAME==bd_47c8_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_0/bd_47c8_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_1/bd_47c8_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_rst_0_0 || ORIG_REF_NAME==bd_47c8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_2/bd_47c8_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_ilmb_0 || ORIG_REF_NAME==bd_47c8_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_3/bd_47c8_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_dlmb_0 || ORIG_REF_NAME==bd_47c8_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_6/bd_47c8_lmb_bram_I_0_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_9/bd_47c8_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/ip/ip_10/bd_47c8_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_47c8_iomodule_0_0 || ORIG_REF_NAME==bd_47c8_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/bd_0/bd_47c8_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==dpss_zcu102_rx_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/ip_0/dpss_zcu102_rx_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/dpss_zcu102_rx_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/Xilinx/DisplayPort/DisplayPort_1_4_ss2_1_rx_ex_v2020p1/hw/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_zcu102_rx/ip/dpss_zcu102_rx_ddr4_0_0/par/dpss_zcu102_rx_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_zcu102_rx_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
